site:
  name: AstroWind # Lahko spremeniš v ime svojega podjetja
  site: 'https://astrowind.vercel.app' # Spremeni v svojo domeno
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: AstroWind
    template: '%s — AstroWind'
  description: "\U0001F680 Primerno za startup podjetja, mala podjetja, SaaS spletne strani, profesionalne portfelije, tržne spletne strani, ciljne strani in bloga."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: AstroWind
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@arthelokyo'
    site: '@arthelokyo'
    cardType: summary_large_image

i18n:
  language: sl # Spremenjeno iz 'en' v 'sl' za slovenščino
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Glavna pot do bloga (lahko spremeniš v 'clanki')
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'kategorija' # Spremenjeno iz 'category' v 'kategorija'
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'oznaka' # Spremenjeno iz 'tag' v 'oznaka'
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
